branch-defaults:
  master:
    environment: qstweetsuite-dev
global:
  application_name: tweetsuite
  default_ec2_keyname: ts_keypair
  default_platform: Python 2.7
  default_region: us-east-1
  profile: eb-cli
  sc: git
