branch-defaults:
  master:
    environment: myflaskrapp-env2
global:
  application_name: myflaskrapp
  default_ec2_keyname: null
  default_platform: Python 2.7
  default_region: us-east-1
  profile: eb-cli
  sc: git
