branch-defaults:
  aws-branch:
    environment: null
  master:
    environment: tweetsuite
  phase1.2:
    environment: tweetsuite-test
    group_suffix: null
global:
  application_name: tweetsuite-dev
  default_ec2_keyname: ts_keypair
  default_platform: Python 2.7
  default_region: us-east-1
  profile: eb-cli
  sc: git
